# Generated by Django 6.0.3 on 2026-03-10 14:34

import django.db.models.deletion
from django.db import migrations, models


def create_departments(apps, schema_editor):
    Department = apps.get_model("helpdesk", "Department")
    for name in [
        "Development",
        "R&D",
        "Design",
        "Debuggers",
        "Testers",
        "Exicutioners",
    ]:
        Department.objects.get_or_create(name=name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_student_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design'), ('Debuggers', 'Debuggers'), ('Testers', 'Testers'), ('Exicutioners', 'Exicutioners')], max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='helpdesk.department'),
        ),
        migrations.RunPython(create_departments, noop_reverse),
    ]
