# Generated by Django 6.0.3 on 2026-03-10 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
