# Generated by Django 6.0.3 on 2026-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_ticket_user_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Development', 'Development'), ('R&D', 'R&D'), ('Design', 'Design'), ('Debuggers', 'Debuggers'), ('Testers', 'Testers'), ('Exicutioners', 'Exicutioners'), ('Extortioners', 'Extortioners')], max_length=60, unique=True),
        ),
    ]
