# Generated by Django 6.0.3 on 2026-03-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assiged_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='helpdesk.student'),
        ),
    ]
